In [6]:
%matplotlib inline
import numpy as np
import matplotlib.pylab as plt

# 勾配
def numerical_gradient(f, x):
    h = 1e-4
    grad = np.zeros_like(x)
    
    for idx in range(x.size):
        tmp_val = x[idx]
        # calc f(x+h)
        x[idx] = tmp_val + h
        fxh1 = f(x)
        # calc f(x-h)
        x[idx] = tmp_val - h
        fxh2 = f(x)
        
        grad[idx] = (fxh1 - fxh2) / (2*h)
        x[idx] = tmp_val
    
        return grad

    
# 勾配法
def gradient_descent(f, init_x, lr=0.01, step_num=100):
    x = init_x
    
    for i in range(step_num):
        grad = numerical_gradient(f, x)
        x -= lr * grad
    
    return x


def function_2(x):
    return x[0]**2 + x[1]**2


init_x = np.array([-3.0, 4.0])
print(gradient_descent(function_2, init_x, lr=1e-10, step_num=100))

[-2.99999994  4.        ]


In [12]:
# ニューラルネットワークに対する勾配
import sys, os
sys.path.append(os.pardir)
import numpy as np
from common.functions import softmax, cross_entropy_error
from common.gradient import numerical_gradient

class SimpleNet:
    def __init__(self):
        self.W = np.random.randn(2, 3)
    
    def predict(self, x):
        return np.dot(x, self.W)
    
    def loss(self, x, t):
        z = self.predict(x)
        y = softmax(z)
        loss = cross_entropy_error(y, t)
        
        return loss

net = SimpleNet()
print(net.W)

[[-0.05330114 -0.69245103  0.90221905]
 [ 0.61889441  0.33227967  0.39187739]]


In [13]:
x = np.array([0.6, 0.9])
p = net.predict(x)
print(p)

[ 0.52502428 -0.11641892  0.89402108]


In [14]:
np.argmax(p)

2

In [15]:
t = np.array([0, 0, 1])
net.loss(x, t)

0.72051250133145894

In [16]:
def f(W):
    return net.loss(x, t)

dW = numerical_gradient(f, net.W)
print(dW)

[[ 0.20182891  0.10626938 -0.30809828]
 [ 0.30274336  0.15940406 -0.46214743]]
